Numpy: Library for numerical computing/processing. 
It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It's widely used in the tasks that involve numerical data manipulation and analysis.

1. N-dimensional arrays (ndarrays): Efficient array objects that can store data in multiple dimensions.
2. Element-wise operations: You can perform mathematical operations directly on arrays without needing to write loops.



NumPy is faster than regular Python lists :

1. Contiguous Memory Allocation: NumPy arrays are stored in a single, contiguous block of memory, while Python lists are made up of pointers to individual objects scattered across memory. This allows NumPy to perform operations more efficiently because it can access data in a predictable and optimized manner.

2. Optimized C and Fortran Code: Under the hood, NumPy is written in C and Fortran, which are much faster languages for numerical computations than Python. When you perform operations on NumPy arrays, you're executing highly optimized, compiled code rather than interpreting Python bytecode.

3. Vectorization: NumPy supports vectorized operations, meaning it can apply operations to entire arrays (or parts of arrays) without explicit loops. This avoids the overhead of Python's loop constructs, and the operation is carried out in compiled code, which is much faster.

4. Efficient Memory Handling: NumPy arrays require less memory per element compared to Python lists because they store data in a more compact way. NumPy also offers more efficient data types, allowing for better use of memory (e.g., float32 vs. float64).

6. Parallelism: Some NumPy functions internally take advantage of parallel computing to speed up processing on multicore machines, especially when using libraries like OpenBLAS or MKL (Math Kernel Library), which handle linear algebra operations.


import numpy as np

In [2]:
import numpy as np

In [3]:
print(np.__version__)

1.26.4


In [4]:
# 1- D ndarray

numlist = [1,2,3,4,5,6]  # list
print(type(numlist))

arrnp = np.array(numlist) # creating an ndarray from list
print(arrnp)
print(type(arrnp))

print(numlist.__class__)
print(arrnp.__class__)

print(arrnp.dtype) # type of data we have in array
print(arrnp.ndim) # dimesion of the array, 1-D, 2-D ....
print(arrnp.shape) # shape of ndarray => (6,) => number of elements in the 1-D array
print(len(arrnp))

<class 'list'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>
int32
1
(6,)
6


In [5]:
# Accessing the ndarray

print(arrnp[0])
print(arrnp[1])
print(arrnp[2])

1
2
3


In [6]:
# 2-D ndarrays

numlist = [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
          ]  # 2-D list

arrnp = np.array(numlist) # creating an ndarray from list
print(arrnp)
print(type(arrnp))
print(numlist.__class__)
print(arrnp.__class__)
print(arrnp.dtype) # type of data we have in array
print(arrnp.ndim) # dimesion of the array, 1-D, 2-D ....
print(arrnp.shape) # shape of ndarray => (rows, cols) => (3,4) => 3*4 matrix
print(len(arrnp)) # no of rows in the array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
<class 'list'>
<class 'numpy.ndarray'>
int32
2
(3, 4)
3


In [7]:
# Accessing 2-D array

print(arrnp[0][2])
print(arrnp[1][3])
print(arrnp[2][0])

3
8
9


In [8]:
# re-shaping (re-arranging the data ) of 2-D ndarray

# 3*4 => 12 => 1*12, 12*1, 2*6, 6*2, 4*3

print(arrnp)  # original rows => 3,  col=> 4

print(arrnp.reshape(4,3)) # rows => 4,  col=> 3

print(arrnp.reshape(2,6)) # rows => 2,  col=> 6

print(arrnp.reshape(6,2)) # rows => 6,  col=> 2

print(arrnp.reshape(12,1)) # rows => 12,  col=> 1

print(arrnp.reshape(1,12)) # rows => 1,  col=> 12

# print(arrnp.reshape(5,2)) # rows => 5,  col=> 3  Not allowed


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [9]:
# arange : returns the evenly spaced numbers within a given interval
# Syntax : arange([start],stop,[step]) => ndarray
# Defaults : start=>0 step=1
# stop is excluded

arr = np.arange(10)   # generates from 0 till stop-1 (0 => 10-1=9)  start=0, stop=10, step=1
print(arr)
print(type(arr))

arr = np.arange(1, 10)   # generates from 1 till stop-1 (1 => 10-1=9)  start=1, stop=10, step=1
print(arr)
print(type(arr))

arr = np.arange(1, 10, 2)   # generates from 1 till stop-1 (1 => 10-1=9)  start=1, stop=10, step=2
print(arr)
print(type(arr))


[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
[1 3 5 7 9]
<class 'numpy.ndarray'>


In [10]:
# ones(), zeros(), empty() => returns the ndarray based on given shape and type
# ones(shape, dtype) => default dtype=float64
# zeros(shape, dtype) => default dtype=float64
# empty(shape, dtype) => default dtype=float64

arrZ = np.zeros([2,5])
print(arrZ)
print(arrZ.dtype)

arrZ = np.zeros([2,5], dtype=np.int32) #int32
print(arrZ)

arrO = np.ones([2,5])
print(arrO)
print(arrO.dtype)

arrO = np.ones([2,5], dtype=np.int16)
print(arrO)
print(arrO.dtype)

arrE = np.empty([3,4], dtype=np.int32)
print(arrE)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
float64
[[1 1 1 1 1]
 [1 1 1 1 1]]
int16
[[ 538976288  538976288 1751343429 2003792416]
 [ 543584032  543193184 1919968626 1852142437]
 [1629516660 1918989856 1818386793 1629498469]]


In [11]:
# linspace => returns the even spaced numbers over a specified interval
# Syntax : linspace(start, stop, numSamples(deafult=50), retstep(True/False), endpoint(True/False)=> True, dtype)

arrLin = np.linspace(1, 20) # start=1, endpoint=20, numSamples=50, endppoint=True
print(arrLin)

arrLin = np.linspace(1, 20, 5) # start=1, endpoint=20, numSamples=5, endppoint=True
print(arrLin)

arrLin = np.linspace(1, 20, 5) # start=1, endpoint=20, numSamples=5, endppoint=True
print(arrLin)

arrLin = np.linspace(1, 20, 5, endpoint=False) # start=1, endpoint=20, numSamples=5, endppoint=False
print(arrLin)

arrLin, step = np.linspace(1, 20, 5, endpoint=False, retstep=True) # start=1, endpoint=20, numSamples=5, endppoint=False
print(arrLin, step)

arrLin = np.linspace(1, 20, 5, endpoint=False, retstep=True) # start=1, endpoint=20, numSamples=5, endppoint=False
print(arrLin[0], arrLin[1])


[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]
[ 1.    5.75 10.5  15.25 20.  ]
[ 1.    5.75 10.5  15.25 20.  ]
[ 1.   4.8  8.6 12.4 16.2]
[ 1.   4.8  8.6 12.4 16.2] 3.8
[ 1.   4.8  8.6 12.4 16.2] 3.8


In [12]:
# logspace => returns the even spaced numbers over the log scale
# default value for 
# the base =10
# logspace(start, stop,numSamples, endpoint, base=10.0, dtype)

arrLin = np.linspace(2, 4, 5)
print(arrLin)

arrlg = np.logspace(2, 4, 5)
print(arrlg)



[2.  2.5 3.  3.5 4. ]
[  100.           316.22776602  1000.          3162.27766017
 10000.        ]


In [13]:
import functools
import warnings
import operator
import types
from . import numeric as _nx

y = np.linspace(2, 4, 5)
base = np.expand_dims(10, axis=0)

print(base)

x =_nx.power(base, y).astype(dtype, copy=False)
print(x)



ImportError: attempted relative import with no known parent package

In [67]:
# eye => identity matrix => diagonal elements will be 1 and other will be 0

arr = np.eye(4) # 4*4
print(arr)

arr = np.eye(3,4) # 3*4
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [69]:
# diag() => ndaray => with diagonal elemnts as specified
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [73]:
# Random => random sample within 0 to 1
arr = np.random.rand(10) # 10 random uniform samples
print(arr)

arr = np.random.randn(10) # Gaussian standard normal samples
print(arr)


[0.30361278 0.99447257 0.7651222  0.47035023 0.53806125 0.91719084
 0.0494156  0.83365765 0.17717101 0.72276161]
[ 2.01557692 -0.29028844 -0.34247762  0.40122169  0.62777402  1.48443268
  0.31311727  0.61754327 -0.06266201  0.11044485]


In [78]:
# Accessing and modification of ndarray values
arr = np.diag([1,2,3,4])
print(arr)

print(arr[1][1])   # Accessing 

arr[1, 1] = 10  # Modifying the numbers at given [row, col] position
print(arr)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
2
[[ 1  0  0  0]
 [ 0 10  0  0]
 [ 0  0  3  0]
 [ 0  0  0  4]]


In [84]:
# Slicing (same as that of string)
# [start:end:step] , end is always excluded


# 1-D 
arr = np.array([2,3,4,5,6,7,8,9])
print(arr)
print(arr[1:5])
print(arr[:3])
print(arr[-3:-1])
print(arr[::5])

# 2-D 
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
print(arr[2])
print(arr[2, 1:4]) # [11,12,13,14,15] => [12,13,14]
print(arr[0:2, 2]) # [1,2,3,4,5],[6,7,8,9,10] => [3,8] fetching pos 2 from each of of the outcome
print(arr[0:2, 1:4]) # [1,2,3,4,5],[6,7,8,9,10] => [[2 3 4] [7 8 9]]


[2 3 4 5 6 7 8 9]
[3 4 5 6]
[2 3 4]
[7 8]
[2 7]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[11 12 13 14 15]
[12 13 14]
[3 8]
[[2 3 4]
 [7 8 9]]


In [87]:
# slice => how to slice a sequence
# slice(start, end, step)

arr = np.array([2,3,4,5,6,7,8,9])
sliceObj = slice(2,6,2)
print(sliceObj)

print(arr[sliceObj])

slice(2, 6, 2)
[4 6]


In [89]:
# slicing and assignment
arr = np.array([1,2,3,4,5,6,7])
arr[2:6] = 10
print(arr)

[ 1  2 10 10 10 10  7]


In [92]:
# Transposing an array

arr = np.array([2,3,4,5,6,7,8,9]) # 1-D
arrT = arr.T
print(arrT) # No effect, the array remains the same. 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])    # 2-D
print(arr)
arrT = arr.T
print(arrT)


[2 3 4 5 6 7 8 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


In [98]:
# Reversing an ndarray

a = np.arange(11)
b = np.arange(6)

print(a)
print(b)
print(a[::-1])  # Reversing the array a
print(b[::-1])  # Reversing the array b

print(a[5:])
# assign the reversed 'array b' to sliced portion of 'array a'
a[5:] = b[::-1]

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5]
[10  9  8  7  6  5  4  3  2  1  0]
[5 4 3 2 1 0]
[ 5  6  7  8  9 10]
[0 1 2 3 4 5 4 3 2 1 0]


In [100]:
# Boolean indexing
arr = np.array([1,2,3,4,5,6,7])
print(arr[arr>5]) # [6,7]



[6 7]


In [103]:
# Mathematical operations + Boolean checks

arr = np.array([1,2,3,4,5,6,7])
print(arr[arr%2==0]**2)



[ 4 16 36]


In [106]:
# Iteration 1-D

arr = np.array([1,2,3,4,5,6,7])
for x in arr:
    print (x)

1
2
3
4
5
6
7


In [108]:
# Iteration 2-D
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [110]:
# nditer

arr = np.array([1,2,3,4,5,6,7])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7


In [14]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [20]:
# Copy and view 

# Copy
arr = np.array([10,20,30,40,50])
x = arr.copy() # copied array

# print(np.delete(arr, 0))  # remove item from 0th position 

#Validation : 1 : Getting the address
print(id(arr))  # id's are different , so a different object
print(id(x)) # id's are different , so a different object

# Validation : 2 : Modifiying the array
arr[3] = 60
print(arr)
print(x)

2460847774128
2460850908848


In [25]:
# View 
arr_v = np.array([10,20,30,40,50])
x_v = arr.view() # view

#Validation : 1 : Getting the address
print(id(arr_v))  # id's are different , so a different object
print(id(x_v)) # id's are different , so a different object

# Validation : 2 : Modifiying through original array
arr_v[3] = 60
print(arr_v)
print(x_v)

# Validation : 2 : Modifiying through view
x_v[3] = 10
print(arr_v)
print(x_v)

2460851448176
2460851447984
[10 20 30 60 50]
[10 20 10 10 50]
[10 20 30 60 50]
[10 20 10 10 50]


In [29]:
arr1 = np.array([[1,2],[6,7]]) # 2-D
arr2 = np.array([[3,4],[10,11]])

print(arr1)
print(arr2)

arr_joined = np.concatenate((arr1, arr2)) # row-wise concatenation, along x-axis (axis=0) (default)
print(arr_joined)

# Dimensions of the arrays should be same
arr_joined = np.concatenate((arr1, arr2), axis=1) # column-wise concatenation, along y-axis (axis=1)
print(arr_joined)


[[1 2]
 [6 7]]
[[ 3  4]
 [10 11]]
[[ 1  2]
 [ 6  7]
 [ 3  4]
 [10 11]]
[[ 1  2  3  4]
 [ 6  7 10 11]]


In [34]:
arr = np.array([1,2,3,4,5,6])

split_arr = np.array_split(arr, 3)
print(split_arr)

split_arr = np.array_split(arr, 8)
print(split_arr)

split_arr = np.split(arr, 4) # splits array into given parts , error out when equal division is not possible
print(split_arr)


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int32), array([], dtype=int32)]


ValueError: array split does not result in an equal division

In [48]:
# Searching of an element
arr = np.array([1,2,3,4,5,6])
pos_arr = np.where(arr == 4) # gives the position of value 4 in array, arr
print(pos_arr[0][0])


3


In [62]:
# Mathematical function

# dimension should be same
arr1 = ([[1,2,3,4,5],[6,7,8,9,10]])
#arr2 = ([[2,2,2,2,2]])
arr2 = ([[1,1,1,1,1]])

print(arr1, arr2)

s = np.add(arr1, arr2)
print(s)

sub = np.subtract(arr1, arr2)
print(sub)

m = np.multiply(arr1, arr2)
print(m)

d = np.divide(arr1, arr2)
print(d)

print(np.reciprocal(arr1))

print(np.power(arr1, arr2))

print(np.min(arr1))

print(np.max(arr1))

print(np.mod(arr1, arr2))

print(np.mean(arr1))

print(np.median(arr1))

print(np.std(arr1))

print(np.sin(arr1))

print(np.cos(arr1))



[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]] [[1, 1, 1, 1, 1]]
[[ 2  3  4  5  6]
 [ 7  8  9 10 11]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
[[1 0 0 0 0]
 [0 0 0 0 0]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
10
[[0 0 0 0 0]
 [0 0 0 0 0]]
5.5
5.5
2.8722813232690143
[[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]]
[[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
 [ 0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153]]


In [63]:
arr = np.array([2.6, 1.2, 3.7, 4.8])
print(np.floor(arr))
print(np.ceil(arr))

[2. 1. 3. 4.]
[3. 2. 4. 5.]
